import {privateJSON,identity,isAdmin,offlineState,prepareOffline} from './private-api.js';
import {installVariedades} from './variedades.js';
import {laraDetail} from './lara.js';
import {installWeather} from './weather.js';
import {installHarvestPlan} from './harvest-plan.js';
import {installCosecha} from './cosecha-ui.js';
import {installSatellite} from './satellite.js';
import {loadFieldData,installLabores} from './labores.js';
import {installRotation} from './rotation.js';
import {installMeasure} from './measure.js';
import {installHaciendaLabels} from './hacienda-labels.js';
import {distance,contains,acceptPoint,normalize} from './geo.js';
import {allRecords,putRecord,getMeta,setMeta} from './store.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),icon=n=>`<svg><use href="#i-${n}"/></svg>`;
const fmt=(n,d=1)=>n===null||n===undefined||n===''?'Sin dato':Number(n).toLocaleString('es-CO',{maximumFractionDigits:d});
const date=v=>!v?'Sin dato':typeof v==='string'&&/^\d{4}-\d{2}-\d{2}/.test(v)?v.slice(0,10).split('-').reverse().join('/'):new Date(v).toLocaleDateString('es-CO');const dist=d=>d>=1000?(d/1000).toLocaleString('es-CO',{maximumFractionDigits:2})+' km':Math.round(d)+' m';
let features=[],byId=new Map(),layers=new Map(),filtered=[],map,layerGroup,selected=null,gps=null,watch=null,gpsMarker,gpsCircle,trackLine,recording=false,route=null,records=[],plan=[],follow=false,basemap='contornos',tiles=null,swReady=null,installPrompt=null,syncing=false,storageOK=true,wake=null,recordBusy=false;
let harvestPlanUI=null,harvestUI=null,measurement=null,laboresUI=null,satelliteUI=null,fieldData=null,rotation=null;
let satelliteActive=false;
let refreshHaciendaLabels=()=>{};
let lastTick=0,activeElapsed=0,timer=0,toastTimer=0;
const groupColors={CV:'#0072B2',PR:'#238443',CP:'#8E44AD',CA:'#D55E00',CO:'#B38A00',CU:'#C43C79'};
const groupName=f=>f.properties.grupoTenencia||'Sin dato';
const groupColor=f=>groupColors[groupName(f)]||'#64748b';
const baseStyle=f=>harvestUI?.style(f)||(satelliteActive?{color:'#77877f',weight:1.7,fillColor:'#e4e7e5',fillOpacity:1}:null)||({color:groupColor(f),weight:1.7,fillColor:groupColor(f),fillOpacity:.28});
const selectedStyle=f=>({...baseStyle(f),color:'#18221f',weight:4,fillOpacity:harvestUI?.isActive()||satelliteActive?baseStyle(f).fillOpacity:.55});
function satellitePaint(active){satelliteActive=active;for(const [id,l] of layers)l.setStyle(id===selected?selectedStyle(byId.get(id)):baseStyle(byId.get(id)));}
document.addEventListener('satellite-start',()=>satellitePaint(true));
document.addEventListener('satellite-clear',()=>satellitePaint(false));
function updateHaciendas(){const g=$('tenencia').value,old=$('hacienda').value;const hs=new Map(features.filter(f=>!g||groupName(f)===g).map(f=>[f.properties.codHacienda,f.properties.hacienda]));$('hacienda').innerHTML='<option value="">Todas las haciendas ('+hs.size+')</option>'+[...hs].sort((a,b)=>a[1].localeCompare(b[1],'es')).map(([id,n])=>`<option value="${esc(id)}">${esc(n)} · ${esc(id)}</option>`).join('');$('hacienda').value=hs.has(old)?old:'';}
function renderLegend(){const counts=new Map();for(const f of filtered)counts.set(groupName(f),(counts.get(groupName(f))||0)+1);$('tenencia-legend').innerHTML=[...counts].sort().map(([g,n])=>`<span><i style="background:${groupColors[g]||'#64748b'}"></i><b>${esc(g)}</b> ${fmt(n,0)}</span>`).join('')||'<span>Sin resultados</span>';}

function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4500);}
function tab(name){if(name==='indices'&&satelliteUI){satelliteUI.open();return;}document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.tab-content').forEach(x=>x.hidden=x.id!=='tab-'+name);$('sidebar').classList.add('open');}
function closeDetail(){$('detail').hidden=true;document.body.classList.remove('detail-open');}
function network(){const on=navigator.onLine;$('connection').textContent=offlineState()?'Copia de campo':on?'En línea':'Sin conexión';$('connection').classList.toggle('off',!on);if(!on&&tiles){map.removeLayer(tiles);tiles=null;basemap='contornos';toast('Sin señal: continúan disponibles los polígonos descargados.');}}
function saveFailed(){storageOK=false;if(recording)stopRecording();toast('No se pudo guardar en el equipo. Descarga un respaldo antes de continuar.');$('sync-status').textContent='Error de almacenamiento. Descarga un respaldo.';}
async function saveRecord(r){r.updatedAt=Date.now();r.pending=false;await putRecord(structuredClone(r));const i=records.findIndex(x=>x.id===r.id);if(i<0)records.push(r);else records[i]=r;syncStatus();}
function syncStatus(msg){$('sync-status').textContent=msg||'Registros cifrados en este teléfono';}
async function synchronize(){syncStatus();renderNotes();renderHistory();}

function filter(){const terms=normalize($('search').value).split(/\s+/).filter(Boolean),h=$('hacienda').value,g=$('tenencia').value;filtered=features.filter(f=>(!g||groupName(f)===g)&&(!h||f.properties.codHacienda===h)&&terms.every(t=>f._search.includes(t)));$('result-count').textContent=`${fmt(filtered.length,0)} suertes`;
 $('map-heading').textContent=h?byId.get(filtered[0]?.id)?.properties.hacienda||'Selección':'Mayagüez';$('map-total').textContent=fmt(filtered.length,0)+' suertes';
 for(const [id,layer] of layers){const visible=(!g||groupName(byId.get(id))===g)&&(!h||byId.get(id).properties.codHacienda===h)&&terms.every(t=>byId.get(id)._search.includes(t));if(visible&&!layerGroup.hasLayer(layer))layerGroup.addLayer(layer);if(!visible&&layerGroup.hasLayer(layer))layerGroup.removeLayer(layer);}
 renderList();renderLegend();refreshHaciendaLabels(filtered);}
let listLimit=70;
function renderList(){const rows=filtered.slice(0,listLimit);$('lot-list').innerHTML=rows.length?rows.map(f=>{const p=f.properties;return `<button class="lot-row ${selected===f.id?'active':''}" data-lot="${f.id}"><span class="lot-icon" style="color:${groupColor(f)};border-color:${groupColor(f)}">${icon('map')}</span><span class="lot-main"><b>${esc(p.hacienda)}</b><small>${esc(p.grupoTenencia)} · ${esc(p.variedad)} · ${esc(p.id)}</small></span><span class="lot-number">${esc(p.suerte)}<small>SUERTE</small></span></button>`;}).join('')+(filtered.length>listLimit?'<button id="more-lots" class="text-btn full mt">Mostrar más suertes</button>':''):'<div class="empty">No se encontraron suertes. Prueba con otra hacienda o código.</div>';$('more-lots')?.addEventListener('click',()=>{listLimit+=100;renderList();});}
function showExtent(){if(layerGroup.getLayers().length)map.fitBounds(layerGroup.getBounds(),{padding:[45,65]});closeDetail();$('sidebar').classList.remove('open');}
function selectLot(id,zoom=true){const f=byId.get(id);if(!f)return false;if(selected&&layers.has(selected))layers.get(selected).setStyle(baseStyle(byId.get(selected)));selected=id;const layer=layers.get(id);if(!layerGroup.hasLayer(layer))layerGroup.addLayer(layer);layer.setStyle(selectedStyle(f)).bringToFront();if(zoom)map.fitBounds(layer.getBounds(),{paddingTopLeft:[30,70],paddingBottomRight:[30,window.innerWidth<700?290:230],maxZoom:17});renderDetail();laboresUI?.select(id);satelliteUI?.select(id);renderList();$('sidebar').classList.remove('open');return true;}
function renderDetail(){if(!selected)return;const p=byId.get(selected).properties;const planned=plan.some(x=>x.id===selected);$('detail').hidden=false;document.body.classList.add('detail-open');const fields=[['Grupo Tenencia',p.grupoTenencia||'Sin dato'],['Nombre Grupo de Abonos',p.nombreGrupoAbonos||'Sin dato en el Excel'],['Variedad',p.variedad],['Área reportada',fmt(p.area,2)],['Edad reportada',fmt(p.edad,2)+' meses'],['TCH última cosecha',fmt(p.tch,2)],['Número de cortes',fmt(p.cortes,0)],['Última cosecha',date(p.cosecha)],['Suelo',p.suelo||'Sin dato'],['Topografía',p.topografia||'Sin dato'],['Entre surcos',p.surcos?fmt(p.surcos,2)+' m':'Sin dato']];
 $('detail').innerHTML=`<div class="detail-top"><div><span class="eyebrow">${esc(p.id)}</span><h2>${esc(p.hacienda)}</h2><p class="subtitle">Suerte <b>${esc(p.suerte)}</b> · <span class="group-badge"><i style="background:${groupColor(byId.get(selected))}"></i>${esc(p.grupoTenencia)}</span></p></div><button id="close-detail" class="icon-btn" aria-label="Cerrar ficha">${icon('close')}</button></div><dl class="detail-grid">${fields.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>${harvestUI?.isActive()?'':laraDetail(p,fieldData.lara)}${harvestUI?.detail(selected)||''}${harvestUI?.isActive()?harvestPlanUI?.button(selected)||'':''}<button id="detail-jobs" class="secondary full">Ver labores del ciclo</button><p class="small-info">Datos del Excel aportado. Edad sin actualización automática. Área: unidad por confirmar.</p><button id="detail-note" class="primary full">${icon('plus')}Registrar hallazgo</button><div class="row-actions"><button id="detail-plan" class="secondary">${planned?'Ver en mi recorrido':'Añadir al recorrido'}</button><button id="detail-complete" class="secondary">Marcar revisada</button></div>`;
 if($('detail-transport'))$('detail-transport').onclick=()=>harvestUI?.openTransport(selected);$('detail-jobs').onclick=()=>{laboresUI?.select(selected);closeDetail();tab('labores');};$('close-detail').onclick=closeDetail;$('detail-note').onclick=()=>openNote(selected);$('detail-plan').onclick=()=>{if(!planned)addPlan(selected);tab('recorrido');closeDetail();};$('detail-complete').onclick=()=>{markDone(selected);closeDetail();};}
async function addPlan(id){if(!plan.some(x=>x.id===id)){plan.push({id,done:false});await setMeta('plan',plan).catch(saveFailed);renderPlan();toast('Suerte añadida al recorrido.');}}
async function markDone(id){if(!plan.some(x=>x.id===id))plan.push({id,done:false});const item=plan.find(x=>x.id===id);item.done=!item.done;await setMeta('plan',plan).catch(saveFailed);renderPlan();toast(item.done?'Suerte marcada como revisada.':'Suerte pendiente de revisión.');}
function renderPlan(){$('plan-count').textContent=plan.filter(x=>!x.done).length;$('plan-list').innerHTML=plan.length?plan.map((item,i)=>{const p=byId.get(item.id)?.properties;if(!p)return '';return `<div class="plan-row"><button class="round-btn ${item.done?'done':''}" data-done="${item.id}" aria-label="${item.done?'Marcar pendiente':'Marcar revisada'}">${item.done?'✓':i+1}</button><button class="plan-open" data-lot="${item.id}">${esc(p.hacienda)} · ${esc(p.suerte)}<small>${item.done?'Revisión completada':'Pendiente'} · ${esc(p.id)}</small></button><button class="remove" data-remove="${item.id}" aria-label="Quitar del recorrido">×</button></div>`;}).join(''):'<div class="empty">Tu recorrido está vacío.<br>Abre una suerte y añádela aquí.</div>';}
function openNote(id=selected){if(!storageOK){toast('No hay almacenamiento disponible. Descarga un respaldo.');return;}if(!id){toast('Selecciona primero una suerte en el mapa o buscador.');tab('lotes');return;}$('note-form').reset();$('note-lot').value=id;const valid=gps&&Date.now()-gps.time<60000;$('note-location').textContent=valid?`Ubicación GPS actual: ${gps.lat.toFixed(5)}, ${gps.lng.toFixed(5)} · ±${Math.round(gps.acc)} m. Se vinculará a la suerte elegida.`:'Sin posición GPS reciente: el hallazgo se vinculará a la suerte elegida, sin coordenadas.';$('note-dialog').showModal();}
async function photoData(file){if(!file)return null;if(file.size>25e6)throw Error('La foto supera 25 MB. Selecciona una más pequeña.');const url=URL.createObjectURL(file);try{const img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(Error('No se pudo abrir la foto. Usa JPG o PNG.'));i.src=url;});const scale=Math.min(1,1400/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.78);}finally{URL.revokeObjectURL(url);}}
$('note-form').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{const lotId=$('note-lot').value;if(!byId.has(lotId))throw Error('Selecciona una suerte válida.');const valid=gps&&Date.now()-gps.time<60000;const note={id:crypto.randomUUID(),type:'note',lotId,text:$('note-text').value.trim(),category:$('note-category').value,severity:$('note-severity').value,photo:await photoData($('note-photo').files[0]),location:valid?{lat:gps.lat,lng:gps.lng,acc:gps.acc}:null,createdAt:Date.now()};if(!note.text)throw Error('Escribe la observación.');await saveRecord(note);$('note-dialog').close();renderNotes();toast('Hallazgo guardado.');void synchronize();}catch(err){toast(err.message);}finally{btn.disabled=false;}};
function renderNotes(){const notes=records.filter(r=>r.type==='note'&&!r.deleted).sort((a,b)=>b.createdAt-a.createdAt);$('notes-count').textContent=notes.length;$('notes-list').innerHTML=notes.length?notes.map(n=>{const p=byId.get(n.lotId)?.properties;return `<article class="note-card"><span class="severity ${esc(n.severity)}">${esc(n.category)} · ${esc(n.severity)}</span><h3>${esc(p?.hacienda||n.lotId)} · ${esc(p?.suerte||'')}</h3><p>${esc(n.text)}</p>${n.photo?`<img src="${esc(n.photo)}" alt="Fotografía del hallazgo" loading="lazy">`:''}<small>${date(n.createdAt)} · ${n.location?'Con ubicación GPS':'Sin coordenadas GPS'}</small><div class="note-footer"><button class="text-btn" data-lot="${n.lotId}">Ver suerte</button><button class="text-btn" data-delete="${n.id}">Eliminar</button></div></article>`;}).join(''):'<div class="empty">Aún no hay hallazgos.<br>Registra tu primera observación en una suerte.</div>';}
async function startGPS(){if(watch!==null){follow=true;if(gps)map.setView([gps.lat,gps.lng],17);return;}if(!navigator.geolocation){toast('Este navegador no permite usar GPS.');return;}follow=true;$('gps-readout').innerHTML=icon('gps')+'<span>Buscando posición GPS…</span>';
 watch=navigator.geolocation.watchPosition(onPosition,e=>{let m=e.code===1?'Permite la ubicación en los ajustes del navegador.':e.code===2?'Ubicación no disponible. Prueba al aire libre.':'El GPS tarda en responder. Esperando una nueva posición…';$('gps-readout').innerHTML=icon('gps')+'<span>'+m+'</span>';toast(m);if(e.code===1){navigator.geolocation.clearWatch(watch);watch=null;$('locate').classList.remove('active');if(recording)stopRecording();}}, {enableHighAccuracy:true,maximumAge:1000,timeout:20000});$('locate').classList.add('active');}
function onPosition(position){const c=position.coords;gps={lat:c.latitude,lng:c.longitude,acc:c.accuracy,time:position.timestamp,speed:c.speed};if(!gpsMarker){gpsMarker=L.circleMarker([gps.lat,gps.lng],{radius:7,color:'white',weight:3,fillColor:'#287de2',fillOpacity:1}).addTo(map);gpsCircle=L.circle([gps.lat,gps.lng],{radius:gps.acc,color:'#287de2',weight:1,fillOpacity:.07}).addTo(map);}else{gpsMarker.setLatLng([gps.lat,gps.lng]);gpsCircle.setLatLng([gps.lat,gps.lng]).setRadius(gps.acc);}if(follow){map.setView([gps.lat,gps.lng],Math.max(map.getZoom(),16));follow=false;}
 const matches=features.filter(f=>contains(f,gps.lng,gps.lat));const label=matches.length===1?matches[0].properties.hacienda+' · '+matches[0].properties.suerte:matches.length>1?'Límite compartido: selecciona la suerte':'Fuera de las suertes cargadas';$('gps-readout').innerHTML=icon('gps')+`<span>±${Math.round(gps.acc)} m · ${esc(label)}</span>`;
 if(recording&&route&&!recordBusy){const last=route.points.at(-1);if(acceptPoint(route.breakNext?null:last,gps)){recordBusy=true;const segmentStart=!last||route.breakNext||gps.time-last.time>60000;if(last&&!segmentStart)route.distance+=distance(last,gps);route.breakNext=false;route.points.push({...gps,segmentStart,lotId:matches.length===1?matches[0].id:null});route.elapsed=activeElapsed;saveRecord(route).then(()=>renderTrack()).catch(saveFailed).finally(()=>recordBusy=false);}else if(gps.acc>50)$('record-status').textContent='Precisión baja (±'+Math.round(gps.acc)+' m). Esperando una posición mejor para registrar.';}}
async function startRecording(){if(!storageOK)return toast('El almacenamiento del equipo no está disponible.');if(!route){route={id:crypto.randomUUID(),type:'route',createdAt:Date.now(),points:[],distance:0,elapsed:0,endedAt:null};await saveRecord(route);await setMeta('activeRoute',route.id);}route.endedAt=null;route.breakNext=true;recording=true;activeElapsed=route.elapsed||0;lastTick=Date.now();$('record').innerHTML='■ Detener recorrido';$('record').classList.add('stop');$('record-status').textContent='Registro activo. Mantén la app visible y la pantalla encendida.';await startGPS();try{wake=await navigator.wakeLock?.request('screen');}catch{}timer=setInterval(()=>{const now=Date.now();activeElapsed+=now-lastTick;lastTick=now;renderRouteStats();},1000);toast('Recorrido iniciado. Se registra al obtener una posición precisa.');}
async function stopRecording(){if(!recording)return;recording=false;clearInterval(timer);activeElapsed+=Date.now()-lastTick;route.elapsed=activeElapsed;route.endedAt=Date.now();await saveRecord(route).catch(()=>{storageOK=false;});await wake?.release().catch(()=>{});wake=null;$('record').innerHTML=icon('route')+'Continuar recorrido';$('record').classList.remove('stop');$('record-status').textContent='Recorrido detenido y guardado. Puedes continuar o iniciar uno nuevo.';renderRouteStats();void synchronize();}
function renderRouteStats(){$('route-distance').textContent=dist(route?.distance||0);const secs=Math.floor((recording?activeElapsed:route?.elapsed||0)/1000);$('route-time').textContent=String(Math.floor(secs/60)).padStart(2,'0')+':'+String(secs%60).padStart(2,'0');}
function renderTrack(){if(trackLine)map.removeLayer(trackLine);if(route?.points?.length){const segments=[];for(const p of route.points){if(p.segmentStart||!segments.length)segments.push([]);segments.at(-1).push([p.lat,p.lng]);}trackLine=L.polyline(segments,{color:'#287de2',weight:4}).addTo(map);}renderRouteStats();if(recording)$('record-status').textContent=`Registro activo · ${route.points.length} puntos GPS. Pantalla encendida.`;}
function renderHistory(){const rs=records.filter(r=>r.type==='route'&&r.id!==route?.id&&r.points?.length).sort((a,b)=>b.createdAt-a.createdAt);$('history-list').innerHTML=rs.length?rs.map(r=>`<div class="history-row"><span>${date(r.createdAt)}<small>${dist(r.distance)} · ${r.points.length} puntos</small></span><button class="text-btn" data-export="${r.id}">Exportar</button></div>`).join(''):'<p class="small-info">Los recorridos anteriores aparecerán aquí.</p>';}
function download(name,content,type){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),10000);}
function exportRoute(r=route){if(!r?.points?.length)return toast('Aún no hay puntos GPS para exportar.');const head=['fecha_hora','latitud','longitud','precision_m','codigo_suerte','inicio_tramo'];const lines=r.points.map(p=>[new Date(p.time).toISOString(),p.lat,p.lng,p.acc,p.lotId||'',p.segmentStart?'1':'0']);download('Mayaguez_recorrido_'+new Date(r.createdAt).toISOString().slice(0,10)+'.csv','\ufeff'+[head,...lines].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8');}
function installation(){const standalone=window.matchMedia('(display-mode: standalone)').matches||navigator.standalone;if(standalone)return toast('Campo ya está abierto como aplicación.');if(installPrompt){installPrompt.prompt();installPrompt=null;return;}$('help-title').textContent='Instalar Campo';$('help-content').innerHTML='<div class="help-step"><b>iPhone · Safari</b><p>Abre este enlace en Safari, toca Compartir y selecciona “Agregar a pantalla de inicio”. Activa “Abrir como app” si aparece.</p></div><div class="help-step"><b>Android · Chrome</b><p>Abre este enlace en Chrome, entra al menú ⋮ y selecciona “Instalar aplicación” o “Añadir a pantalla de inicio”.</p></div><div class="help-step"><b>Antes de salir a campo</b><p>Permite la ubicación y pulsa “Preparar para campo”. Los polígonos y fichas quedarán cifrados para 72 horas. Los fondos satelital y de calles requieren internet.</p></div><p class="small-info">Primera versión web instalable. El registro GPS requiere mantener la app visible y la pantalla encendida.</p>';$('help-dialog').showModal();}
function help(){$('help-title').textContent='Campo · Mayagüez';$('help-content').innerHTML='<div class="help-step"><b>Propiedad de Mayagüez</b><p>Versión 1.20 · Índices Sentinel-2 · Labores del ciclo y actualización de Excel · Medición de áreas y distancias · Nombres de haciendas · Colores por Grupo Tenencia · 3.034 suertes de 423 haciendas. Solo se incluyen códigos coincidentes del shape y el Excel suministrados.</p></div><div class="help-step"><b>Cómo recorrer</b><p>Busca una hacienda, abre una suerte y añádela a tu recorrido. En Recorrido, inicia el registro GPS. Marca una suerte como revisada únicamente después de inspeccionarla.</p></div><div class="help-step"><b>GPS y caminos</b><p>El mapa muestra tu ubicación y el trayecto realizado. No calcula rutas transitables ni navegación giro a giro. La precisión depende del teléfono y del entorno. Mantén la app abierta y visible.</p></div><div class="help-step"><b>Información agronómica</b><p>La edad es la reportada en el Excel, sin fecha de corte confirmada. El TCH corresponde a la última cosecha. El encabezado de área no especifica unidad; se conserva el valor original.</p></div><div class="help-step"><b>Guardado en el teléfono</b><p>Los registros y fotos se guardan en este navegador y equipo. No se sincronizan entre teléfonos. Descarga un respaldo completo y restáuralo en el otro equipo cuando lo necesites. Borrar los datos del navegador puede eliminar los registros.</p></div><div class="help-step"><b>Sin conexión</b><p>Pulsa Preparar para campo con internet y confirma tu contraseña. Podrás volver a abrir sin señal durante 72 horas con esa contraseña. La baja de un usuario se verifica al reconectar. Los nuevos índices y el clima necesitan internet.</p></div>';$('help-dialog').showModal();}
async function offline(){if(recording)return toast('Detén el recorrido antes de preparar el equipo.');$('offline-dialog').showModal();$('offline-password').value='';}
$('offline-form').onsubmit=async e=>{e.preventDefault();const btn=$('offline-prepare');btn.disabled=true;try{if(!navigator.onLine)throw Error('Necesitas conexión para preparar el equipo.');$('offline-progress').textContent='Preparando aplicación…';const reg=await window.campoSW;if(!reg?.active)throw Error('El navegador no permite la descarga de la aplicación.');await new Promise((resolve,reject)=>{const ch=new MessageChannel();const t=setTimeout(()=>reject(Error('La descarga de la aplicación tardó demasiado.')),120000);ch.port1.onmessage=e=>{clearTimeout(t);e.data.ok?resolve():reject(Error(e.data.error));};reg.active.postMessage({type:'PREPARE_OFFLINE'},[ch.port2]);});const result=await prepareOffline($('offline-password').value,(n,total)=>$('offline-progress').textContent=`Guardando bases protegidas ${n}/${total}…`);await navigator.storage?.persist?.();$('offline-status').textContent='Lista hasta '+new Date(result.expires).toLocaleString('es-CO');$('offline-progress').textContent='Descarga completa. Puedes cerrar y volver a abrir la app sin señal, usando tu correo y contraseña. Vigente hasta '+new Date(result.expires).toLocaleString('es-CO');$('offline-password').value='';}catch(e){$('offline-progress').textContent=e.message;}finally{btn.disabled=false;}};
async function importBackup(file){if(!file)return;try{if(file.size>100e6)throw Error('El archivo supera 100 MB.');const data=JSON.parse(await file.text());if(data.app!=='mayaguez-campo'||!Array.isArray(data.records))throw Error('Este archivo no es un respaldo de Campo.');for(const r of data.records){if(!r||!['note','route'].includes(r.type)||typeof r.id!=='string'||!/^[a-zA-Z0-9-]{8,80}$/.test(r.id)||!Number.isFinite(r.updatedAt))throw Error('El respaldo contiene un registro inválido.');if(r.type==='note'&&(!byId.has(r.lotId)||typeof r.text!=='string'||r.text.length>3000||(r.photo&&!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(r.photo))))throw Error('Hallazgo incompatible con esta base.');if(r.type==='route'&&(!Array.isArray(r.points)||r.points.some(p=>!Number.isFinite(p.lat)||!Number.isFinite(p.lng)||Math.abs(p.lat)>90||Math.abs(p.lng)>180)))throw Error('Trayecto inválido.');}if(!confirm('¿Restaurar '+data.records.length+' registros? Se conservarán los registros actuales más recientes.'))return;for(const r of data.records){const current=records.find(x=>x.id===r.id);if(!current||r.updatedAt>current.updatedAt){await saveRecord(r);}}renderNotes();renderHistory();toast('Respaldo restaurado.');void synchronize();}catch(e){toast(e.message);}}
async function init(){try{
 if(!window.L)throw Error('No se pudo cargar el mapa. Recarga con conexión.');
 map=L.map('map',{zoomControl:false,preferCanvas:true,attributionControl:true});L.control.zoom({position:'bottomright'}).addTo(map);L.control.scale({imperial:false,position:'bottomright'}).addTo(map);
 const data=await privateJSON('lotes.json');features=data.features;fieldData=await loadFieldData();for(const f of features){if(fieldData.properties[f.id])f.properties={...f.properties,...fieldData.properties[f.id]};}features.sort((a,b)=>a.properties.hacienda.localeCompare(b.properties.hacienda,'es')||a.properties.suerte.localeCompare(b.properties.suerte,'es',{numeric:true}));byId=new Map(features.map(f=>{f._search=normalize([f.properties.hacienda,f.properties.codHacienda,f.properties.suerte,f.properties.grupoTenencia,f.id].join(' '));return[f.id,f];}));
 layerGroup=L.featureGroup().addTo(map);for(const f of features){const layer=L.geoJSON(f,{style:baseStyle,onEachFeature:(ft,l)=>{l.on('click',e=>{if(measurement?.isActive()){measurement.add(e);L.DomEvent.stopPropagation(e);return;}selectLot(ft.id,false);});l.bindTooltip(esc(ft.properties.hacienda)+' · '+esc(ft.properties.suerte)+' · Grupo '+esc(ft.properties.grupoTenencia),{className:'lot-label',sticky:true});}});layers.set(f.id,layer);layerGroup.addLayer(layer);}map.fitBounds(layerGroup.getBounds(),{padding:[45,70]});
 satelliteUI=installSatellite({map,features,selectLot,toast});rotation=installRotation(map,$('rotate-toggle'),$('rotate-panel'));laboresUI=installLabores({data:fieldData,features,selectLot,toast,isRecording:()=>recording});
 installVariedades({features,data:fieldData,selectLot,showJobs:id=>{laboresUI.select(id);closeDetail();tab('labores');},openIndices:()=>satelliteUI.open()});
 harvestUI=installCosecha({data:fieldData,map,features,toast,isRecording:()=>recording,onModeChange:active=>{if(active){closeDetail();satelliteUI.clear();$('search').value='';$('tenencia').value='';$('hacienda').value='';updateHaciendas();filter();}},onPaint:()=>{for(const [id,l] of layers)l.setStyle(id===selected?selectedStyle(byId.get(id)):baseStyle(byId.get(id)));if(selected&&!$('detail').hidden)renderDetail();}});
 installWeather({map,getSelected:()=>selected?byId.get(selected):null});
 harvestPlanUI=await installHarvestPlan({data:fieldData,features,toast,selectLot,onChange:()=>{if(selected&&!$('detail').hidden)renderDetail();}});
 const groups=[...new Set(features.map(groupName))].sort();$('tenencia').innerHTML='<option value="">Todos los grupos ('+groups.length+')</option>'+groups.map(g=>`<option value="${esc(g)}">${esc(g)}</option>`).join('');updateHaciendas();$('note-lot').innerHTML=features.map(f=>`<option value="${f.id}">${esc(f.properties.hacienda)} · ${esc(f.properties.suerte)} (${f.id})</option>`).join('');
 measurement=installMeasure(map,{button:$('measure-toggle'),panel:$('measure-panel'),onOpen:()=>{closeDetail();$('sidebar').classList.remove('open');}});refreshHaciendaLabels=installHaciendaLabels(map,features,$('hacienda-names'));filter();network();$('map-loading').hidden=true;
 try{records=await allRecords();plan=(await getMeta('plan')||[]).filter(x=>byId.has(x.id));const rid=await getMeta('activeRoute');route=records.find(r=>r.id===rid&&r.type==='route')||null;if(route){$('record').innerHTML=icon('route')+'Continuar recorrido';$('record-status').textContent='Se recuperó el último recorrido. Pulsa Continuar para reactivar el GPS.';renderTrack();}}catch{saveFailed();}
 renderPlan();renderNotes();renderHistory();renderRouteStats();void synchronize();
 const offlineCopy=offlineState();if(offlineCopy)$('offline-status').textContent='Copia del '+new Date(offlineCopy.downloadedAt).toLocaleString('es-CO')+' · vence '+new Date(offlineCopy.expires).toLocaleString('es-CO');document.dispatchEvent(new Event('campo-ready'));
 }catch(e){$('map-loading').innerHTML='<b>No se pudo abrir el mapa</b><span>'+esc(e.message)+'</span><button class="primary" id="retry-map">Reintentar</button>';$('retry-map').onclick=()=>location.reload();}}
$('search').oninput=()=>{clearTimeout(window.searchTimer);window.searchTimer=setTimeout(()=>{listLimit=70;filter();},150);};$('tenencia').onchange=()=>{updateHaciendas();listLimit=70;filter();showExtent();};$('hacienda').onchange=()=>{listLimit=70;filter();showExtent();};$('show-all').onclick=showExtent;$('extent').onclick=()=>{$('tenencia').value='';updateHaciendas();$('hacienda').value='';$('search').value='';filter();showExtent();};$('locate').onclick=()=>void startGPS();$('open-data').onclick=()=>$('data-dialog').showModal();$('data-close').onclick=()=>$('data-dialog').close();$('install').onclick=installation;$('help').onclick=help;$('offline').onclick=offline;$('add-note').onclick=()=>openNote();$('mobile-panel').onclick=()=>tab('lotes');document.querySelector('.sidebar-top').onclick=()=>{if(window.innerWidth<700)$('sidebar').classList.remove('open');};
$('basemap').onclick=()=>{if(!navigator.onLine)return toast('Sin señal: usa los contornos descargados.');if(tiles){map.removeLayer(tiles);tiles=null;}basemap=basemap==='contornos'?'satelite':basemap==='satelite'?'calles':'contornos';if(basemap==='satelite')tiles=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Imágenes © Esri'}).addTo(map);if(basemap==='calles')tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>'}).addTo(map);if(tiles)tiles.on('tileerror',()=>{$('map-total').textContent='Fondo no disponible · usa contornos';});toast(basemap==='contornos'?'Mapa de contornos':basemap==='satelite'?'Fondo satelital · requiere internet':'Mapa de calles · requiere internet');};
$('record').onclick=()=>{(recording?stopRecording():startRecording()).catch(e=>toast(e.message));};$('export-route').onclick=()=>exportRoute();$('new-route').onclick=async()=>{if(recording)await stopRecording();if(route)await saveRecord(route);route=null;activeElapsed=0;await setMeta('activeRoute',null);if(trackLine){map.removeLayer(trackLine);trackLine=null;}$('record').innerHTML=icon('route')+'Iniciar recorrido';$('record-status').textContent='El recorrido anterior se conserva en el historial.';renderRouteStats();renderHistory();};
$('export-backup').onclick=()=>download('Mayaguez_respaldo_'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify({app:'mayaguez-campo',version:1,exportedAt:new Date().toISOString(),records,plan}),'application/json');$('import-backup').onclick=()=>$('backup-file').click();$('backup-file').onchange=e=>void importBackup(e.target.files[0]);
$('sync-status').onclick=()=>void synchronize();$('sync-status').title='Usa Descargar respaldo completo para conservar una copia';
 document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab)tab(b.dataset.tab);if(b.dataset.lot)selectLot(b.dataset.lot);if(b.dataset.close)$(b.dataset.close).close();if(b.dataset.done)await markDone(b.dataset.done);if(b.dataset.remove){plan=plan.filter(x=>x.id!==b.dataset.remove);await setMeta('plan',plan).catch(saveFailed);renderPlan();}if(b.dataset.export)exportRoute(records.find(r=>r.id===b.dataset.export));if(b.dataset.delete&&confirm('¿Eliminar este hallazgo y su foto?')){const n=records.find(r=>r.id===b.dataset.delete);n.deleted=true;await saveRecord(n).catch(saveFailed);renderNotes();void synchronize();}});
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});window.addEventListener('online',()=>{network();void synchronize();});window.addEventListener('offline',network);document.addEventListener('visibilitychange',()=>{if(document.hidden&&recording){void stopRecording();toast('Recorrido pausado al salir de la app. Continúa al regresar.');}else if(!document.hidden)void synchronize();});window.addEventListener('pagehide',()=>{if(route&&recording){route.elapsed=activeElapsed;void saveRecord(route);}});void init();

window.campoBeforeLock=async()=>{if(recording)await stopRecording();if(watch!==null)navigator.geolocation.clearWatch(watch);satelliteUI?.clear();};

$('migrate-legacy').onclick=async()=>{if(recording)return toast('Detén el recorrido primero.');if(!confirm('¿Estos son tus registros de la versión anterior en este equipo? Se copiarán a tu cuenta local cifrada y se retirará la copia anterior sin cifrar. Las bases actuales de Supabase no cambiarán.'))return;try{const {migrateLegacy}=await import('./legacy-migration.js');const result=await migrateLegacy();records=await allRecords();renderNotes();renderHistory();toast(result.count+' registros protegidos.');}catch(e){toast(e.message);}};
