import {login,restore,authorize,unlockVault,logout,clearSession,identity,isAdmin,recover,recoveryFromURL,changePassword,loginOffline,offlineState,forgetOffline,isRemembered,rememberedDeadline,restoreRememberedOffline} from './private-api.js';
const $=id=>document.getElementById(id);let opened=false,closing=false,started=0,recovery=false;
const channel='BroadcastChannel' in window?new BroadcastChannel('campo-private-access'):null;
const status=msg=>{$('auth-status').textContent=msg;};
async function closeAccess(message='Sesión cerrada.',broadcast=false){if(closing)return;closing=true;document.documentElement.classList.add('access-locked');try{await window.campoBeforeLock?.();}catch{}if(broadcast)channel?.postMessage({type:'logout'});await logout();sessionStorage.setItem('campo-login-message',message);location.replace(new URL('./',location.href).href);}
channel?.addEventListener('message',e=>{if(e.data?.type==='logout')void closeAccess('Sesión cerrada en otra pestaña.');});
function applyRole(){const admin=isAdmin()&&!offlineState();for(const id of ['open-data','harvest-save','harvest-green','harvest-yellow','fuel-open','fuel-editor','budget-calculate']){const el=$(id);if(el){el.hidden=!admin;el.disabled=!admin;}}document.body.dataset.role=identity().rol;}
async function openApp(){await unlockVault();started=Date.now();$('auth-password').value='';$('auth-panel').hidden=true;$('campo-root').hidden=false;opened=true;$('account-name').textContent=identity().nombre||identity().email;$('account-role').textContent=identity().rol;await import('./app.js');applyRole();document.addEventListener('campo-ready',applyRole,{once:true});}
$('auth-form').onsubmit=async e=>{e.preventDefault();const b=$('auth-submit');b.disabled=true;status(recovery?'Guardando contraseña…':'Verificando acceso…');try{if(recovery){const p=$('auth-password').value;if(p.length<12)throw Error('Usa una contraseña de al menos 12 caracteres.');await changePassword(p);await logout();recovery=false;$('auth-email').disabled=false;$('auth-submit').textContent='Ingresar';$('auth-password').value='';status('Contraseña actualizada. Ingresa con tu correo y la nueva contraseña.');return;}const email=$('auth-email').value.trim(),password=$('auth-password').value;if(!navigator.onLine)await loginOffline(email,password);else{try{await login(email,password,$('auth-remember').checked);}catch(e){if(e.status){if(e.status===403)await forgetOffline(email);throw e;}await loginOffline(email,password);}}await openApp();}catch(err){if(opened){await closeAccess('No se pudo abrir la app. '+err.message);return;}if(!recovery)clearSession();status(err.status===400?'No se pudo ingresar. Revisa el correo, la contraseña y la confirmación de tu cuenta.':err.message);}finally{b.disabled=false;}};
$('auth-recover').onclick=async()=>{const email=$('auth-email').value.trim();if(!$('auth-email').checkValidity()||!email)return status('Escribe tu correo para recuperar el acceso.');$('auth-recover').disabled=true;try{await recover(email);status('Si la cuenta puede recibir correos, llegará un enlace para restablecer la contraseña.');}catch{status('No se pudo enviar el correo. Contacta al administrador para revisar el servicio de correo de Supabase.');}finally{$('auth-recover').disabled=false;}};
$('account-logout').onclick=()=>void closeAccess('Sesión cerrada.',true);
async function check(){if(!opened||closing)return;if(offlineState()&&Date.now()>offlineState().expires){if(isRemembered()){document.documentElement.classList.add('access-locked');try{await window.campoBeforeLock?.();}catch{}location.reload();return;}return closeAccess('La copia de campo venció. Conéctate para renovarla.');}if(rememberedDeadline()&&Date.now()>rememberedDeadline())return closeAccess('Tu sesión recordada venció. Ingresa nuevamente.');if(!offlineState()&&!rememberedDeadline()&&Date.now()-started>8*3600000)return closeAccess('Tu jornada de acceso terminó. Conéctate e ingresa nuevamente.');if(!navigator.onLine)return;if(offlineState()){try{const response=await fetch('https://hqmbrdifqxdrfptjdqlt.supabase.co/auth/v1/health',{headers:{apikey:'sb_publishable_5ToSNq24dkHxqx2jpKIpQw_Pd0iwRr3'},signal:AbortSignal.timeout(5000),cache:'no-store'});if(response.ok){if(isRemembered()){document.documentElement.classList.add('access-locked');try{await window.campoBeforeLock?.();}catch{}location.reload();}else await closeAccess('Volvió la conexión. Ingresa para validar permisos y cargar las bases vigentes.');}}catch{}return;}try{const old=identity()?.rol;await authorize();if(identity().rol!==old)return closeAccess('Tus permisos cambiaron. Ingresa nuevamente.');}catch(e){if(e.status===400||e.status===401||e.status===403){await forgetOffline(identity()?.email||'');await closeAccess('El acceso venció o fue desactivado. Ingresa nuevamente.');}}}
setInterval(()=>void check(),60000);window.addEventListener('online',()=>void check());document.addEventListener('visibilitychange',()=>{if(!document.hidden)void check();});
try{const msg=sessionStorage.getItem('campo-login-message');sessionStorage.removeItem('campo-login-message');if(msg)status(msg);if(await recoveryFromURL()){recovery=true;$('auth-email').disabled=true;$('auth-email').required=false;$('auth-password').autocomplete='new-password';$('auth-password').minLength=12;$('auth-submit').textContent='Guardar nueva contraseña';status('Escribe tu nueva contraseña (mínimo 12 caracteres).');}else{let ready=false;if(navigator.onLine){try{ready=await restore();}catch(e){if(e.status)throw e;ready=await restoreRememberedOffline();}}else ready=await restoreRememberedOffline();if(ready)await openApp();}}catch(e){if(e.status){await logout();}status(e.message);}
window.addEventListener('pagehide',()=>document.documentElement.classList.add('access-locked'));
window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});

window.addEventListener('online',()=>{if(!opened&&localStorage.getItem('campo-remembered-session-v1'))location.reload();});
