import {harvestAlerts,harvestAlertHtml,todayColombia} from './harvest-alerts.js';
import {getMeta,setMeta} from './store.js';
import {traffic} from './cosecha-model.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const fmt=v=>v==null?'Sin dato':Number(v).toLocaleString('es-CO',{maximumFractionDigits:2});
export function reference(f){const p=f.properties,area=Number.isFinite(p.area)&&p.area>0?p.area:null,tch=Number.isFinite(p.tch)&&p.tch>0?p.tch:null;return {area,tch,tons:area!==null&&tch!==null?area*tch:null};}
export async function installHarvestPlan({data,features,toast,selectLot,onChange}){
 const $=id=>document.getElementById(id),byId=new Map(features.map(f=>[String(f.id),f])),route=data.sucrose?.records||{},saved=await getMeta('harvestPlan').catch(()=>null);let chosen=new Set((saved?.ids||[]).filter(id=>byId.has(id))),saving=false;
 const dist=f=>{const a=[...new Set(features.filter(x=>x.properties.codHacienda===f.properties.codHacienda).map(x=>x.properties.distanciaIngenio).filter(x=>Number.isFinite(x)&&x>=0))].sort((a,b)=>a-b);return {text:a.length===1?fmt(a[0]):a.length?fmt(a[0])+'–'+fmt(a.at(-1)):'Sin dato',value:a.length===1?a[0]:Infinity};};
 const distance=new Map(features.map(f=>[String(f.id),dist(f)]));
 $('harvest-extent').insertAdjacentHTML('afterend','<button id="open-harvest-plan" class="primary full mt">Plan de cosecha</button>');
 document.body.insertAdjacentHTML('beforeend',`<dialog id="harvest-plan-dialog"><div class="dialog-head"><h2>Plan de cosecha</h2><button id="harvest-plan-close" class="icon-btn" aria-label="Cerrar">×</button></div><p class="small-info">Toneladas de referencia histórica = área reportada (ha) × TCH de la última cosecha. No es un aforo ni una predicción de la próxima cosecha.</p><div id="harvest-plan-summary" role="status"></div><p id="harvest-auto-summary" class="small-info"></p><label><input id="harvest-plan-ready" type="checkbox"> Filtrar candidatas sin faltantes ni alertas de ciclo/acceso</label><p class="small-info">La revisión usa las bases cargadas; no certifica que el lote esté listo. Las suertes seleccionadas se conservan aunque tengan alertas.</p><label>Ordenar<select id="harvest-plan-sort"><option value="score">Mejor calificación</option><option value="distance">Menor distancia de hacienda</option></select></label><label>Buscar hacienda o suerte<input id="harvest-plan-search" type="search"></label><label><input id="harvest-plan-only" type="checkbox"> Ver solo seleccionadas</label><p class="small-info">Candidatas: colores marcados en Ruta de sacarosa. Las seleccionadas permanecen en el plan aunque cambies filtros.</p><button id="harvest-plan-add" class="secondary full">Añadir candidatas visibles</button><div id="harvest-plan-list"></div><button id="harvest-plan-export" class="primary full mt">Descargar propuesta CSV</button><button id="harvest-plan-clear" class="text-btn full mt">Vaciar selección</button></dialog>`);
 function candidates(){const search=$('harvest-plan-search').value.trim().toLocaleLowerCase('es'),only=$('harvest-plan-only').checked;return features.filter(f=>{const id=String(f.id),r=route[id],c=r?traffic(r.score,data.harvestSettings):null,visible=c&&document.querySelector('#harvest-colors input[value="'+c+'"]:checked');return (only?chosen.has(id):visible||chosen.has(id))&&(!$('harvest-plan-ready').checked||chosen.has(id)||harvestAlerts(f.properties,r).issues.length===0)&&(!search||[f.properties.hacienda,f.properties.suerte,id].join(' ').toLocaleLowerCase('es').includes(search));}).sort((a,b)=>{const x=String(a.id),y=String(b.id);if($('harvest-plan-sort').value==='distance'){const d=distance.get(x).value-distance.get(y).value;if(d)return d;}return (route[y]?.score??-1)-(route[x]?.score??-1)||x.localeCompare(y);});}
 function summary(){let area=0,tons=0,covered=0,missing=0;for(const id of chosen){const r=reference(byId.get(id));area+=r.area||0;if(r.tons==null)missing++;else{tons+=r.tons;covered+=r.area;}}return {area,tons,covered,missing};}
 function render(){const s=summary();const checks=[...chosen].map(id=>harvestAlerts(byId.get(id).properties,route[id]));$('harvest-auto-summary').textContent=checks.filter(a=>a.issues.length).length+' seleccionadas con alertas · '+checks.filter(a=>a.days!==null&&a.days>0).length+' con evaluación anterior a hoy ('+todayColombia()+'). El semáforo conserva la nota del Excel.';$('open-harvest-plan').textContent='Plan de cosecha · '+chosen.size+' suertes';$('harvest-plan-summary').innerHTML=`<b>${chosen.size} suertes · ${fmt(s.area)} ha con área válida</b><p>${fmt(s.tons)} t de referencia histórica${s.missing?' · subtotal parcial':''}</p><small>Cobertura del cálculo: ${fmt(s.covered)} ha. ${s.missing} suertes sin área o TCH positivo; no se interpretan como cero.</small>`;$('harvest-plan-list').innerHTML=candidates().map(f=>{const id=String(f.id),r=reference(f),score=route[id]?.score,date=route[id]?.date;return `<article class="harvest-plan-row"><label><input type="checkbox" data-plan-id="${esc(id)}" ${chosen.has(id)?'checked':''} ${saving?'disabled':''}><b>${esc(f.properties.hacienda)} · ${esc(f.properties.suerte)}</b></label><p>Calificación ${fmt(score)} / 5 · ${fmt(r.area)} ha · ${distance.get(id).text} km de hacienda</p><p>Último TCH: ${fmt(r.tch)} · ${fmt(r.tons)} t históricas de referencia</p><small>Última cosecha: ${esc(f.properties.cosecha?String(f.properties.cosecha).slice(0,10).split('-').reverse().join('/'):'Sin fecha')} · Evaluación sacarosa: ${esc(date||'Sin fecha')}${route[id]?.preharvest==null?' · Sin precosecha':''}${!route[id]?' · Fuera de ruta actual':''}</small>${harvestAlertHtml(f.properties,route[id])}<button class="text-btn" data-plan-map="${esc(id)}">Ver en mapa</button></article>`;}).join('')||'<p>Sin suertes para estos filtros.</p>';$('harvest-plan-export').disabled=!chosen.size;}
 async function change(next){if(saving)return;saving=true;try{await setMeta('harvestPlan',{ids:[...next],updatedAt:new Date().toISOString()});chosen=next;onChange();}catch(e){toast('No se guardó el plan: '+e.message);}finally{saving=false;render();}}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-harvest-toggle]');if(b){const id=b.dataset.harvestToggle,next=new Set(chosen);next.has(id)?next.delete(id):next.add(id);void change(next);}});
 $('harvest-plan-list').onchange=e=>{const id=e.target.dataset.planId;if(!id)return;const next=new Set(chosen);e.target.checked?next.add(id):next.delete(id);void change(next);};$('harvest-plan-list').onclick=e=>{const b=e.target.closest('[data-plan-map]');if(b){$('harvest-plan-dialog').close();selectLot(b.dataset.planMap);}};
 $('open-harvest-plan').onclick=()=>{render();$('harvest-plan-dialog').showModal();};$('harvest-plan-close').onclick=()=>$('harvest-plan-dialog').close();$('harvest-plan-sort').onchange=$('harvest-plan-only').onchange=$('harvest-plan-ready').onchange=render;$('harvest-plan-search').oninput=render;$('harvest-plan-add').onclick=()=>{const next=new Set(chosen);candidates().forEach(f=>next.add(String(f.id)));void change(next);};$('harvest-plan-clear').onclick=()=>{if(confirm('¿Vaciar la selección del plan?'))void change(new Set());};
 $('harvest-plan-export').onclick=()=>{const rows=[['Tipo de estimación','Código','Hacienda','Suerte','Área ha','Último TCH histórico','Toneladas referencia histórica','Fecha última cosecha','Calificación final','Fecha evaluación sacarosa','Distancia hacienda km','Observaciones','Dias desde evaluacion','Menor calificacion','Alertas automaticas']];for(const id of chosen){const f=byId.get(id),p=f.properties,r=reference(f);rows.push(['Referencia histórica; no aforo',id,p.hacienda,p.suerte,r.area,r.tch,r.tons,p.cosecha,route[id]?.score,route[id]?.date,distance.get(id).text,r.tons==null?'Sin área o TCH válido':!route[id]?'Fuera de ruta actual':'',harvestAlerts(p,route[id]).days,harvestAlerts(p,route[id]).weakest.map(x=>x[0]+' '+x[1]).join('; '),harvestAlerts(p,route[id]).issues.join('; ')]);}const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Propuesta_cosecha_referencia_historica.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};
 render();return {button:id=>`<button class="primary full mt" data-harvest-toggle="${esc(id)}">${chosen.has(String(id))?'Quitar del plan de cosecha':'Añadir al plan de cosecha'}</button>`};
}
