const te=new TextEncoder(),td=new TextDecoder();let database;
function db(){return database??=new Promise((resolve,reject)=>{const r=indexedDB.open('campo-offline-private-v1-'+encodeURIComponent(new URL('./',location.href).pathname),1);r.onupgradeneeded=()=>{r.result.createObjectStore('packages');r.result.createObjectStore('credentials');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function read(store,id){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(store).objectStore(store).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function emailId(email){const bytes=await crypto.subtle.digest('SHA-256',te.encode(email.trim().toLowerCase()));return Array.from(new Uint8Array(bytes),n=>n.toString(16).padStart(2,'0')).join('');}
async function passwordKey(password,salt){const material=await crypto.subtle.importKey('raw',te.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:600000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export async function encode(value,key,context){const iv=crypto.getRandomValues(new Uint8Array(12));return {iv,data:await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:te.encode(context)},key,te.encode(JSON.stringify(value)))};}
export async function decode(blob,key,context){return JSON.parse(td.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:blob.iv,additionalData:te.encode(context)},key,blob.data)));}
export async function importVault(hex){return crypto.subtle.importKey('raw',Uint8Array.from(hex.match(/../g),x=>parseInt(x,16)),{name:'AES-GCM'},false,['encrypt','decrypt']);}
export async function saveOffline({email,password,profile,hex,key,files}){const now=Date.now(),expires=now+72*3600000,id=await emailId(email),salt=crypto.getRandomValues(new Uint8Array(16));const wrapped=await encode({profile,hex,expires,downloadedAt:now},await passwordKey(password,salt),'credentials:'+id);const bundle=await encode({files,downloadedAt:now},key,'package:'+profile.user_id);const d=await db();await new Promise((res,rej)=>{const t=d.transaction(['packages','credentials'],'readwrite');t.objectStore('packages').put(bundle,profile.user_id);t.objectStore('credentials').put({...wrapped,salt},id);t.oncomplete=res;t.onerror=()=>rej(t.error);t.onabort=()=>rej(t.error);});return {expires,downloadedAt:now};}
export async function openOffline(email,password){const id=await emailId(email),wrapped=await read('credentials',id);if(!wrapped)throw Error('Este equipo no está preparado para ese usuario. Ingresa con conexión y pulsa Preparar para campo.');let access;try{access=await decode(wrapped,await passwordKey(password,wrapped.salt),'credentials:'+id);}catch{throw Error('No se pudo abrir la copia. Revisa el correo y la contraseña utilizados al prepararla.');}if(Date.now()>access.expires||Date.now()<access.downloadedAt-300000)throw Error('La copia sin conexión venció. Conéctate para renovarla (vigencia: 72 horas).');const key=await importVault(access.hex),blob=await read('packages',access.profile.user_id);if(!blob)throw Error('La descarga está incompleta. Prepara nuevamente el equipo con internet.');const bundle=await decode(blob,key,'package:'+access.profile.user_id);return {...access,key,files:bundle.files};}
export async function removeOffline(email){const id=await emailId(email),d=await db();await new Promise((res,rej)=>{const t=d.transaction('credentials','readwrite');t.objectStore('credentials').delete(id);t.oncomplete=res;t.onerror=()=>rej(t.error);});}
// Acceso opcional en un dispositivo de confianza. La contraseña nunca se guarda.
export async function saveDeviceAccess({profile,hex,expires}){const key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']);const encrypted=await encode({profile,hex,expires},key,'remembered-device');const d=await db();await new Promise((res,rej)=>{const t=d.transaction('credentials','readwrite');t.objectStore('credentials').put({key,...encrypted},'remembered-device');t.oncomplete=res;t.onerror=()=>rej(t.error);});}
export async function removeDeviceAccess(){const d=await db();await new Promise((res,rej)=>{const t=d.transaction('credentials','readwrite');t.objectStore('credentials').delete('remembered-device');t.oncomplete=res;t.onerror=()=>rej(t.error);});}
export async function openDeviceAccess(){const row=await read('credentials','remembered-device');if(!row)return null;const a=await decode(row,row.key,'remembered-device');if(Date.now()>a.expires)throw Error('La sesión recordada venció. Ingresa nuevamente.');const key=await importVault(a.hex),blob=await read('packages',a.profile.user_id);if(!blob)throw Error('Para entrar sin señal, primero prepara la descarga de campo.');const bundle=await decode(blob,key,'package:'+a.profile.user_id),expires=Math.min(a.expires,bundle.downloadedAt+72*3600000);if(Date.now()>expires||Date.now()<bundle.downloadedAt-300000)throw Error('La copia de campo venció. Conéctate para renovarla.');return {...a,key,files:bundle.files,downloadedAt:bundle.downloadedAt,expires};}
