import {identity,localKey,publishData} from './private-api.js';
let dbPromise,dbUser;
function db(){const uid=identity()?.user_id;if(!uid)throw Error('Inicia sesión.');if(dbUser&&dbUser!==uid){dbPromise?.then(d=>d.close());dbPromise=null;}dbUser=uid;return dbPromise??=new Promise((resolve,reject)=>{const r=indexedDB.open('mayaguez-private-v1-'+encodeURIComponent(new URL('./',location.href).pathname)+'-'+uid,1);r.onupgradeneeded=()=>{r.result.createObjectStore('records',{keyPath:'id'});r.result.createObjectStore('meta');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function encrypt(value,context){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(context)},localKey(),new TextEncoder().encode(JSON.stringify(value)));return {iv,data};}
async function decrypt(value,context){if(value===undefined)return undefined;return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:value.iv,additionalData:new TextEncoder().encode(context)},localKey(),value.data)));}
export async function allRecords(){const d=await db();const rows=await new Promise((res,rej)=>{const r=d.transaction('records').objectStore('records').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});return Promise.all(rows.map(r=>decrypt(r,'records:'+r.id)));}
export async function putRecord(value){const encrypted=await encrypt(value,'records:'+value.id);const d=await db();return new Promise((res,rej)=>{const t=d.transaction('records','readwrite');t.objectStore('records').put({id:value.id,...encrypted});t.oncomplete=()=>res();t.onerror=()=>rej(t.error);t.onabort=()=>rej(t.error||Error('No se pudo guardar'));});}
export async function getMeta(key){if(key==='fieldDataOverride')return null;const d=await db();const value=await new Promise((res,rej)=>{const r=d.transaction('meta').objectStore('meta').get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});return decrypt(value,'meta:'+key);}
export async function setMeta(key,value){if(key==='fieldDataOverride'){if(value)await publishData(value);return;}const encrypted=await encrypt(value,'meta:'+key);const d=await db();return new Promise((res,rej)=>{const t=d.transaction('meta','readwrite');t.objectStore('meta').put(encrypted,key);t.oncomplete=()=>res();t.onerror=()=>rej(t.error);});}
